# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171112_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='hey', unique=True),
            preserve_default=False,
        ),
    ]
